//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrewTurn.Wiki.Web.Localization.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Editor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Editor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScrewTurn.Wiki.Web.Localization.Common.Editor", typeof(Editor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnBiggerMarkup_AlternateText {
            get {
                return ResourceManager.GetString("btnBiggerMarkup_AlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase editor size.
        /// </summary>
        public static string btnBiggerMarkup_ToolTip {
            get {
                return ResourceManager.GetString("btnBiggerMarkup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnBiggerMarkupVisual_AlternateText {
            get {
                return ResourceManager.GetString("btnBiggerMarkupVisual_AlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase editor size.
        /// </summary>
        public static string btnBiggerMarkupVisual_ToolTip {
            get {
                return ResourceManager.GetString("btnBiggerMarkupVisual_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string btnPreview_Text {
            get {
                return ResourceManager.GetString("btnPreview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnPreview_ToolTip {
            get {
                return ResourceManager.GetString("btnPreview_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnSmallerMarkup_AlternateText {
            get {
                return ResourceManager.GetString("btnSmallerMarkup_AlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease editor size.
        /// </summary>
        public static string btnSmallerMarkup_ToolTip {
            get {
                return ResourceManager.GetString("btnSmallerMarkup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnSmallerMarkupVisual_AlternateText {
            get {
                return ResourceManager.GetString("btnSmallerMarkupVisual_AlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease editor size.
        /// </summary>
        public static string btnSmallerMarkupVisual_ToolTip {
            get {
                return ResourceManager.GetString("btnSmallerMarkupVisual_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        public static string btnVisual_Text {
            get {
                return ResourceManager.GetString("btnVisual_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnVisual_ToolTip {
            get {
                return ResourceManager.GetString("btnVisual_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WikiMarkup.
        /// </summary>
        public static string btnWikiMarkup_Text {
            get {
                return ResourceManager.GetString("btnWikiMarkup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string btnWikiMarkup_ToolTip {
            get {
                return ResourceManager.GetString("btnWikiMarkup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblPreview_Text {
            get {
                return ResourceManager.GetString("lblPreview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Warning&lt;/b&gt;: this is only a preview. The content was not saved..
        /// </summary>
        public static string lblPreviewWarning_Text {
            get {
                return ResourceManager.GetString("lblPreviewWarning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblPreviewWarning_ToolTip {
            get {
                return ResourceManager.GetString("lblPreviewWarning_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblSnippets_Text {
            get {
                return ResourceManager.GetString("lblSnippets_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblSnippets_ToolTip {
            get {
                return ResourceManager.GetString("lblSnippets_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblStrings_Text {
            get {
                return ResourceManager.GetString("lblStrings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblWYSIWYG_Text {
            get {
                return ResourceManager.GetString("lblWYSIWYG_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string lblWYSIWYG_ToolTip {
            get {
                return ResourceManager.GetString("lblWYSIWYG_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string txtMarkup_Text {
            get {
                return ResourceManager.GetString("txtMarkup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string txtMarkup_ToolTip {
            get {
                return ResourceManager.GetString("txtMarkup_ToolTip", resourceCulture);
            }
        }
    }
}
